/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GymManagementSystem.view;

/**
 *
 * @author ACER
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfullname = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textnum = new javax.swing.JTextField();
        textpassword = new javax.swing.JPasswordField();
        textconpass = new javax.swing.JPasswordField();
        jregisterbutton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("    ADMIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 135, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("FullName");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 205, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 205, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 205, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 209, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Phone Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 205, -1));

        txtfullname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtfullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfullnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 305, -1));

        textEmail.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });
        getContentPane().add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 305, -1));

        textnum.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnumActionPerformed(evt);
            }
        });
        getContentPane().add(textnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 305, -1));

        textpassword.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(textpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 305, -1));

        textconpass.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textconpass.setText("jPasswordField2");
        textconpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textconpassActionPerformed(evt);
            }
        });
        getContentPane().add(textconpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 305, -1));

        jregisterbutton.setBackground(new java.awt.Color(51, 51, 255));
        jregisterbutton.setForeground(new java.awt.Color(51, 0, 51));
        jregisterbutton.setText("REGISTER");
        jregisterbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jregisterbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jregisterbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 510, 40));

        jButton2.setBackground(new java.awt.Color(0, 204, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, 100, 30));

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 650, 100, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Yellow and Black Modern Fitness Ad Instagram Post (1).png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 1340));

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfullnameActionPerformed

    private void textnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnumActionPerformed

    private void textpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpasswordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:                                       
    try {
        String fullname = txtfullname.getText();
        String email = textEmail.getText();
        String phone = textnum.getText();
        String password = new String(textpassword.getPassword());

        try (java.io.FileWriter writer = new java.io.FileWriter("admin_data.txt", true) // append mode
        ) {
            writer.write(fullname + "," + email + "," + phone + "," + password + "\n");
        }

        javax.swing.JOptionPane.showMessageDialog(this, "Data saved successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error saving data: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }


  


    }//GEN-LAST:event_jButton2ActionPerformed

    private void textconpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textconpassActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textconpassActionPerformed

    private void jregisterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jregisterbuttonActionPerformed
        // TODO add your handling code here:                                                
    String fullname = txtfullname.getText();
    String email = textEmail.getText();
    String phone = textnum.getText();
    String password = new String(textpassword.getPassword());
    String confirmPassword = new String(textconpass.getPassword());

    if(fullname.isEmpty() || email.isEmpty() || phone.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    if(!password.equals(confirmPassword)){
        javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // You can add more validation here (email format, phone number format etc.)

    javax.swing.JOptionPane.showMessageDialog(this, "Registration Successful!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    // Optionally, clear the fields after successful registration
    txtfullname.setText("");
    textEmail.setText("");
    textnum.setText("");
    textpassword.setText("");
    textconpass.setText("");


    

    
    }//GEN-LAST:event_jregisterbuttonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:                                         
    int choice = javax.swing.JOptionPane.showConfirmDialog(this, 
        "Do you want to go to the login page?", 
        "Confirm", 
        javax.swing.JOptionPane.YES_NO_OPTION);

    if (choice == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose();  // Close current Admin window

        // Open the Login window
        // Assuming your login JFrame class is called 'Login'
        Login loginPage = new Login();
        loginPage.setVisible(true);
    }



    }//GEN-LAST:event_jButton4ActionPerformed

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jregisterbutton;
    private java.awt.TextArea textArea1;
    private javax.swing.JTextField textEmail;
    private javax.swing.JPasswordField textconpass;
    private javax.swing.JTextField textnum;
    private javax.swing.JPasswordField textpassword;
    private javax.swing.JTextField txtfullname;
    // End of variables declaration//GEN-END:variables
}


