/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gymmanagesystem.view;

import gymmanagesystem.controller.ReviewController;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JLabel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Font;
import java.awt.Color;

/**
 *
 * @author ACER
 */
public class Reviewpage extends javax.swing.JFrame {
    
    private ReviewController controller;
    private JPanel starPanel;
    private JLabel[] starLabels;
    private int selectedRating = 1;
    private boolean reviewSubmitted = false;

    /**
     * Creates new form Reviewpage
     */
    public Reviewpage() {
        initComponents();
        setupController();
    }
    
    private void setupController() {
        controller = new ReviewController(this);
    }
    
    public void setController(ReviewController controller) {
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Write a Review");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 109, 238, 33));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Rating");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 158, 33));

        // Insert the star rating panel directly under the rating label
        starPanel = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0));
        starPanel.setOpaque(false); // No background
        // Remove border and extra padding
        starLabels = new JLabel[5];
        for (int i = 0; i < 5; i++) {
            starLabels[i] = new JLabel("☆");
            starLabels[i].setFont(new Font("Dialog", Font.BOLD, 40));
            starLabels[i].setForeground(Color.GRAY);
            starLabels[i].setToolTipText("Rate " + (i+1) + " star" + (i==0 ? "" : "s"));
            starLabels[i].setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            final int starIndex = i;
            starLabels[i].addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent e) {
                    if (!reviewSubmitted) setStarRating(starIndex + 1);
                }
                public void mouseEntered(MouseEvent e) {
                    if (!reviewSubmitted) highlightStars(starIndex + 1);
                }
                public void mouseExited(MouseEvent e) {
                    if (!reviewSubmitted) highlightStars(selectedRating);
                }
            });
            starPanel.add(starLabels[i]);
        }
        setStarRating(selectedRating);
        getContentPane().add(starPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 320, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Review Title");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 263, 158, 33));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Your Review");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 465, 158, 33));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 670, 120, 30));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton7.setText("Submit Review");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 666, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 527, 581, 87));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 314, 581, 87));

        jButton8.setBackground(new java.awt.Color(102, 102, 102));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Back ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 744, 90, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/dashboardbackground3.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1530, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (controller != null) {
            controller.backToDashboard();
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (controller != null) {
            controller.submitReview();
        } else {
            JOptionPane.showMessageDialog(this, "Controller not initialized", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (controller != null) {
            controller.cancelReview();
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void setStarRating(int rating) {
        selectedRating = rating;
        for (int i = 0; i < 5; i++) {
            starLabels[i].setText(i < rating ? "★" : "☆");
            starLabels[i].setForeground(i < rating ? Color.ORANGE : Color.GRAY);
        }
    }
    private void highlightStars(int rating) {
        for (int i = 0; i < 5; i++) {
            starLabels[i].setText(i < rating ? "★" : "☆");
            starLabels[i].setForeground(i < rating ? Color.ORANGE : Color.GRAY);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reviewpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reviewpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reviewpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reviewpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reviewpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    // Getter and Setter methods for controller
    public String getRating() {
        return String.valueOf(selectedRating);
    }

    public void setRating(String rating) {
        try {
            int idx = Integer.parseInt(rating);
            setStarRating(Math.max(1, Math.min(idx, 5)));
        } catch (NumberFormatException e) {
            setStarRating(1);
        }
    }

    public String getReviewTitle() {
        return jTextField2.getText();
    }

    public void setReviewTitle(String title) {
        jTextField2.setText(title);
    }

    public String getReviewContent() {
        return jTextField1.getText();
    }

    public void setReviewContent(String content) {
        jTextField1.setText(content);
    }

    public void disableReviewForm() {
        reviewSubmitted = true;
        for (JLabel star : starLabels) star.setEnabled(false);
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jButton7.setEnabled(false);
    }

    public void enableReviewForm() {
        reviewSubmitted = false;
        for (JLabel star : starLabels) star.setEnabled(true);
        jTextField1.setEnabled(true);
        jTextField2.setEnabled(true);
        jButton7.setEnabled(true);
    }
}
