/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gymmanagesystem.view;

import gymmanagesystem.controller.LoginSystemController;
import gymmanagesystem.controller.UserRegistrationController;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import java.awt.Color;

/**
 *
 * @author DELL
 */
public class UserRegisterView extends javax.swing.JFrame {
    private UserRegistrationController controller;
    private Object jLabel8;

    /**
     * Creates new form UserRegister
     */
    public UserRegisterView() {
        initComponents();
        setLocationRelativeTo(null); // Center the window
        jLabel6.setText("Confirm Password"); 
        // Update label text
    }
    
    public void setController(UserRegistrationController controller) {
        this.controller = controller;
        if (controller != null) {
            setupNavigation();
        }
    }
    
    
    public void setupNavigation() {
        // Connect Register button
        registerButton.addActionListener(e -> onRegisterButtonClick());
        
        // Connect Show password buttons
        jButton1.addActionListener(e -> onShowPassword1Click());
        jButton3.addActionListener(e -> onShowPassword2Click());
        
        // Connect Login link
        jButton2.addActionListener(e -> onLoginLinkClick());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fullNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        PasswordField1 = new javax.swing.JPasswordField();
        PasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dobTextField = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("User ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 144, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 206, 37, -1));

        jLabel3.setText("Full name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 222, 59, -1));
        getContentPane().add(fullNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 244, 183, -1));

        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 278, 37, -1));
        getContentPane().add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 294, 183, -1));

        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 334, -1, -1));

        jLabel6.setText("Confirm  password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 411, -1, -1));

        registerButton.setBackground(new java.awt.Color(0, 51, 255));
        registerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register ");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 521, 408, 34));

        jCheckBox1.setText("I agree to all the Terms and Privacy Policies ");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 474, -1, -1));

        jLabel7.setText("Already have an account?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 576, 138, -1));

        jLabel9.setText("Phone Number");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 278, -1, -1));
        getContentPane().add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 294, 199, -1));
        getContentPane().add(PasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 362, 330, 31));
        getContentPane().add(PasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 433, 330, 29));

        jButton1.setText("Show ");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 366, -1, -1));

        jButton3.setText("Show");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 436, -1, -1));
        getContentPane().add(dobTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 244, 208, -1));

        jLabel10.setText("Date of Birth");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 222, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 573, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/Userregisterbgg.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Closes the current window
    LoginSystemView loginView = new LoginSystemView();
    LoginSystemController loginController = new LoginSystemController(loginView);
    loginView.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    public void clearForm() {
        fullNameTextField.setText("");
        emailTextField.setText("");
        phoneTextField.setText("");
        PasswordField1.setText("");
        PasswordField2.setText("");
        dobTextField.setDate(null);
        jCheckBox1.setSelected(false);
    }

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserRegisterView registerView = new UserRegisterView();
                UserRegistrationController controller = new UserRegistrationController(registerView);
                registerView.setController(controller);
                controller.open();
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JPasswordField PasswordField2;
    private com.toedter.calendar.JDateChooser dobTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables

    // Getter methods for controller
    public javax.swing.JTextField getFullNameField() {
        return fullNameTextField;
    }

    public javax.swing.JTextField getEmailField() {
        return emailTextField;
    }

    public javax.swing.JTextField getPhoneField() {
        return phoneTextField;
    }

    public javax.swing.JPasswordField getPasswordField() {
        return PasswordField1;
    }

    public javax.swing.JPasswordField getConfirmPasswordField() {
        return PasswordField2;
    }

    public java.util.Date getDateOfBirthField() {
        return dobTextField.getDate();
    }

    public javax.swing.JCheckBox getTermsCheckBox() {
        return jCheckBox1;
    }

    // Public methods for controller to call directly (no listeners)
    public void onRegisterButtonClick() {
        if (controller != null) {
            controller.handleRegister();
        }
    }
    
    public void onShowPassword1Click() {
        if (controller != null) {
            controller.handleShowPassword(PasswordField1, jButton1);
        }
    }
    
    public void onShowPassword2Click() {
        if (controller != null) {
            controller.handleShowPassword(PasswordField2, jButton3);
        }
    }
    
    public void onLoginLinkClick() {
        if (controller != null) {
            controller.navigateToLogin();
        }
    
    }
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) { 
    if (jCheckBox1.isSelected()) {
        System.out.println("Terms and conditions accepted.");
    } else {
        System.out.println("Terms and conditions not accepted.");
    }
}  
}

