/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gymmangementsystem23.View;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class AdminNotificationView extends javax.swing.JFrame {
    

    /**
     * Creates new form AdminNotificationView
     */
    public AdminNotificationView() {
        initComponents();
        // Set default selected items
     NotificationTypeTextField.setSelectedItem("Announcement");
     TargetAudienceTextField.setSelectedItem("All Members");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        NotificationTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MessageTextField = new javax.swing.JTextField();
        NotificationTypeField = new javax.swing.JLabel();
        NotificationTypeTextField = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        TargetAudienceTextField = new javax.swing.JComboBox<>();
        CancelButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        CreateNotificationTextField = new javax.swing.JLabel();
        CreateNotificationButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Notification Title");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 154, -1, -1));
        getContentPane().add(NotificationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 176, 600, 44));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Message");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, -1));

        MessageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessageTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(MessageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 266, 600, 67));

        NotificationTypeField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NotificationTypeField.setText("Notification Type");
        getContentPane().add(NotificationTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        NotificationTypeTextField.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        NotificationTypeTextField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Announcement", "1", "2", "3", "4", " ", " " }));
        NotificationTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotificationTypeTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NotificationTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 270, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Target Audience");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        TargetAudienceTextField.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        TargetAudienceTextField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Members", "1", "2", "3", "4" }));
        getContentPane().add(TargetAudienceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 310, 30));

        CancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 90, 30));

        SaveButton.setBackground(new java.awt.Color(0, 0, 0));
        SaveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("Save as Draft");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 120, 30));

        CreateNotificationTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreateNotificationTextField.setText("Create Notification");
        getContentPane().add(CreateNotificationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        CreateNotificationButton.setBackground(new java.awt.Color(51, 0, 51));
        CreateNotificationButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CreateNotificationButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateNotificationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/Addsign.png"))); // NOI18N
        CreateNotificationButton.setText(" Create Notification");
        CreateNotificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNotificationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CreateNotificationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 10, 10));

        jLabel5.setText("Create new notification to send to your members.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, 270, 20));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 20, -1));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setText("Schedule for later");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NotificationTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificationTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotificationTypeTextFieldActionPerformed

    private void MessageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MessageTextFieldActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
 JOptionPane.showMessageDialog(this,"Cancelled");
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
JOptionPane.showMessageDialog(this,"Saved");
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CreateNotificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNotificationButtonActionPerformed
     JOptionPane.showMessageDialog(this,"New Notification"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateNotificationButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminNotificationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminNotificationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminNotificationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminNotificationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminNotificationView().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CreateNotificationButton;
    private javax.swing.JLabel CreateNotificationTextField;
    private javax.swing.JTextField MessageTextField;
    private javax.swing.JTextField NotificationTextField;
    private javax.swing.JLabel NotificationTypeField;
    private javax.swing.JComboBox<String> NotificationTypeTextField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JComboBox<String> TargetAudienceTextField;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
